# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderId', models.IntegerField()),
                ('chat', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mobilenumber', models.CharField(max_length=300)),
                ('emailid', models.CharField(max_length=300)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('password', models.IntegerField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(default='pending', max_length=200)),
                ('accessone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=100)),
                ('request', models.CharField(default='Pending', max_length=100)),
                ('userDet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='accesstwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UploadModel'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel'),
        ),
    ]
